"""
Bancos de frases, palabras, vocabulario y plantillas para el Modo Radio
de La Rockola del Carpincho.
Contiene el lore de humedal, modismos rioplatenses, frases horarias,
reacciones de cabina, filtros léxicos y plantillas sintácticas.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Locutores y prosodia
# ---------------------------------------------------------------------------

VOICE_TOMAS = "es-AR-TomasNeural"
VOICE_ELENA = "es-AR-ElenaNeural"
VOICE_MARIA = "es-CR-MariaNeural"
VOICE_VALENTINA = "es-UY-ValentinaNeural"
VOICES = [VOICE_TOMAS, VOICE_ELENA, VOICE_MARIA, VOICE_VALENTINA]

VOICE_NAMES: dict[str, str] = {
	VOICE_TOMAS: "Tomás",
	VOICE_ELENA: "Elena",
	VOICE_MARIA: "María",
	VOICE_VALENTINA: "Valentina",
}

# Prosodia fija por locutor (personajes con impronta propia para sonar naturales y no robóticos)
VOICE_PROSODY: dict[str, dict[str, str]] = {
	VOICE_TOMAS: {
		"rate": "-4%",
		"pitch": "-3Hz",
		"volume": "+0%",
	},
	VOICE_ELENA: {
		"rate": "-6%",
		"pitch": "-4Hz",
		"volume": "+0%",
	},
	VOICE_MARIA: {
		"rate": "+3%",
		"pitch": "+1Hz",
		"volume": "+0%",
	},
	VOICE_VALENTINA: {
		"rate": "+2%",
		"pitch": "+0Hz",
		"volume": "+0%",
	},
}

DEFAULT_TTS_TIMEOUT: float = 12.0
DEFAULT_TTS_RETRIES: int = 3
DEFAULT_BG_VOLUME: float = 0.1

# ---------------------------------------------------------------------------
# Fortunas del Carpincho y Avisos Publicitarios
# ---------------------------------------------------------------------------

CARPINCHO_FORTUNES: list[str] = [
	"Che, no te apurés; el agua siempre llega a la orilla.",
	"Posta: el secreto del éxito carpincho es mate caliente, buena música y cero drama.",
	"Un carpinchazo de tema te arregla cualquier lunes; comprobado científicamente.",
	"Tranqui en el agua; que las olas se las lleven los apurados.",
	"El carpincho no se apura: sabe que el agua siempre llega.",
	"Tomate un mate, bajá un cambio y disfrutá el temazo que viene.",
	"La vida es corta como pata de carpincho: no te hagas drama por pavadas.",
	"No cuentes los mates que te tomás, hacé que cada mate cuente.",
	"Si la vida te tira limones, fijate si conseguís hielo y fernet.",
	"Tranquilo como carpincho en Nordelta.",
	"El secreto de la felicidad: buena música, agua tibia y cero apuro.",
	"Hoy es un gran día para no hacer nada y hacerlo con mucho estilo.",
	"El que madruga encuentra todo cerrado.",
	"No dejes para mañana lo que puedas procrastinar hoy con buena música.",
	"El asado une lo que el lunes separa.",
	"Donde manda carpincho, no manda marinero.",
	"Más vale pájaro en mano... que pájaro volando sobre tu cabeza.",
	"Un tropezón no es caída, pero si nadie te vio, mejor todavía.",
	"El mate dulce no es pecado, pero bueno, sobre gustos no hay nada escrito.",
	"Ojo al piojo: las mejores cosas de la vida te despeinan.",
	"Algún día los carpinchos dominarán el mundo... pero hoy tienen fiaca.",
	"No bombardeen Barrio Norte, pongan cumbia y rocanrol.",
	"Si no hay amor que no haya nada, pero que al menos haya música en La Rockola.",
	"El tiempo no para, pero vos podés frenar un toque a escuchar este temita.",
	"Todo un palo, ya lo ves: la música te salva una y otra vez.",
	"Pronto recibirás una visita inesperada... ojalá traiga facturas.",
	"Tu creatividad te llevará lejos, pero acordate de cargar la SUBE.",
	"Un gran viaje comienza con un solo paso... y una buena playlist.",
	"Sonreí: confundís a tus enemigos y le ponés onda a la tarde.",
	"El oráculo predice que la próxima canción te va a encantar.",
	"Más vale carpincho en laguna que cien mosquitos en la nuca.",
	"El que se va a Sevilla pierde su silla, pero el que se queda baila.",
	"Para el carpincho sabio, cada charco es un jacuzzi.",
	"A caballo regalado no se le miran los dientes, pero a la playlist sí.",
	"No hay mal que dure cien años, ni pena que una cumbia no cure.",
	"Ojo al piojo con los que te dicen que no pongas otro tema.",
	"Si el río suena, es porque un carpincho se tiró de bomba.",
	"Billetera mata galán, pero temazo mata billetera.",
	"El oráculo dice: relajá la mandíbula y metele play.",
	"No te preocupes por el qué dirán: el carpincho toma sol y le importa un comino.",
	"El que busca encuentra... menos las llaves cuando estás apurado.",
	"Mejor solo que mal acompañado, pero con buena música nunca estás solo.",
	"Cuidado con el que te dice que no toma fernet... algo oculta.",
	"La música limpia el alma del polvo de la rutina diaria.",
	"El mate amargo y la música al palo, como manda la ley criolla.",
	"Todo concluye al fin, todo termina... menos esta fiesta en La Rockola.",
	"No llores porque terminó, ponete otro temazo y sonreí.",
	"El oráculo avisa: se viene un temazo de aquellos, prepará el mate.",
	"A seguro se lo llevaron preso, pero al carpincho lo dejaron en el agua.",
	"Lo bueno si breve, dos veces bueno... excepto cuando suena un temazo.",
	"No empujen que hay música y mates para todos.",
	"El que ríe último... probablemente no entendió el chiste.",
	"Las penas se van cantando, o por lo menos se disimulan bastante bien.",
	"El carpincho zen dice: respirá hondo y dejate llevar por el ritmo.",
	"Si la tarde viene pesada, una buena cumbia te la acomoda.",
	"No hay camino a la felicidad: la felicidad es escuchar música entre amigos.",
	"Menos drama y más cumbia, esa es la receta del éxito.",
	"Un sabio dijo una vez... ¡subile el volumen que este tema me encanta!",
	"El oráculo predice: tu día va a mejorar en un cien por ciento con este tema.",
	# Filosofía zen de pantano
	"El carpincho no compite con la corriente: flota con dignidad y que el río haga el esfuerzo.",
	"Conflicto territorial lo tienen los que construyen sobre el humedal; nosotros ya estábamos acá.",
	"Dormir doce horas sobre el lodo no es pereza: es comunión con la madre tierra.",
	"Si un problema no se resuelve tomando un mate al sol, entonces no tiene solución.",
	"Hacete amigo del yacaré: no para abrazarlo, sino para saber bien por dónde nada.",
	"La paz mental es ver pasar la lancha a motor y ni siquiera parpadear.",
	"No le pidas peras al olmo ni velocidad a un roedor de setenta kilos.",
	# Cotidianeidad de humedal, dilemas criollos y refranero refactorizado
	"El que no nada se ahoga, y el que no chupa el mate a tiempo se le enfría la pava.",
	"A seguro se lo llevó la correntada del Paraná, pero al carpincho lo salvó la paciencia.",
	"En casa de herrero, cuchillo de tacuara y la bombilla tapada con yerba barbacuá.",
	"La vida es como remar contra la corriente: si no le metés ritmo, terminás en el juncal de enfrente.",
	"El verdadero dilema nacional no es la grieta: es si el vacío a la estaca se come a punto o jugoso.",
	"No te pelees por quién lavó la bombilla: poné pava nueva y cebate otro con espuma.",
	"Hacer la cola en la orilla para esperar la lancha colectiva enseña más templanza que diez años de yoga.",
	"Con el precio del kilo de yerba por las nubes, al mate se lo estira hasta que parezca sopa de pasto.",
	"La pizza de molde sostiene el alma, pero la de piedra te apura las ganas de seguir bailando.",
	"Mucho hielo en el fernet es de cobarde, pero sin hielo es una locura de verano.",
	"El carpincho no le teme a la sudestada: acomoda las ramas y se echa un sueñito reparador.",
	"Si la lancha te llena de olas el rancho, no te enojes: disfrutá el vaivén y metele otro amargo.",
	"Más vale mate lavado en mano que diez termos importados vacíos.",
	"El que madruga en la isla ve salir el sol, pero el que duerme la siesta llega entero al fogón.",
	"No hay trámite en la orilla que un buen chamamé de fondo no te haga más llevadero.",
	"En la mesa del asado no se discute de política: se discute quién se quedó con el último pedazo de tira.",
	"El secreto de la paz interior: cara de nada, lomo al sol y que el barro tape las malas ondas.",
	"Gato escaldado del agua huye, pero carpincho curtido se tira de panza con cualquier marea.",
	"El mundo gira muy rápido para los que andan a los piques; en el arroyo todo tiene su compás.",
	"El oráculo de la laguna sentencia: si la yerba todavía tiene palo, ese mate aguanta tres vueltas más.",
]

CARPINCHO_ADS: list[str] = [
	"Espacio publicitario: Yerba Mate El Carpincho Mimoso, estacionada dos años en laguna natural. Un mate que te acaricia el alma.",
	"Publicidad: Pastos y Juncos Don Pedro. Los mejores brotes tiernos del Delta para rumiar en la orilla mientras suena La Rockola.",
	"Aviso inmobiliario: Inmobiliaria El Bañado. Venta de lotes con costa propia y vista panorámica a Nordelta. Cero expensas, pura paz.",
	"Publicidad: Protector solar Piel de Carpincho, factor ochenta. Tomate un solazo en la barranca sin quemarte el cuero.",
	"Espacio publicitario: Ponchos y Boinas El Yacaré. Elegancia criolla para las noches frescas en el pajonal.",
	"Aviso comercial: Remises La Nutria. Te cruzamos el río a nado o en canoa. Más rápidos que doradillo en bajante.",
	"Espacio publicitario: Fernet Laguna Negra con dos hielos y coca. El combustible oficial de los carpinchos trasnochadores.",
	"Publicidad: Spa Termal Los Esteros. Baños de fango curativo y masajes con caña tacuara. Salís como nuevo, hecho una seda.",
	"Aviso comercial: Seguros La Madriguera. Si la crecida te llega al cogote, nosotros te cubrimos la cueva. Dormí sin frazada.",
	"Publicidad: Ferretería Don Roedor. Bombas de achique, alambrados olímpicos y machetes para desmalezar la isla.",
	"Espacio publicitario: Barbería y Peluquería Bigote Criollo. Corte degrade, recorte de bigotes y peinado a contrapelo para deslumbrar en la laguna.",
	"Aviso parroquial: Academia Los Carpincheros. Clases de natación sincronizada y flotación tipo tronco para principiantes.",
	"Publicidad: Astilleros La Balsa. Botes a remo, kayaks de madera y balsas de totora con garantía de por vida.",
	"Espacio publicitario: Café de Algarroba y Facturas Don Ceibo. El desayuno ideal antes de tirarse a la sombra a hacer la siesta.",
	"Publicidad: Colchones Sommier Paja Brava. Firmeza garantizada para dormir doce horas seguidas como un señor carpincho.",
	"Aviso comercial: Cervecería Artesanal El Pantano. Con lúpulo silvestre y agua fresca de vertiente isleña. Pedite una pinta bien helada.",
	"Espacio publicitario: Sombreros de Paja Don Bigote. Frescura, sombra y porte gaucho para caminar por el terraplén.",
	"Aviso parroquial: Repelente Chau Mosquito. Para que no te piquen las orejas mientras disfrutás de un buen chamamé.",
	"Publicidad: Panadería La Espiga Verde. Medialunas de grasa calentitas a toda hora para acompañar los amargos.",
	"Espacio publicitario: Neumáticos La Huella. Cámaras inflables para flotar panza arriba toda la tarde en el arroyo.",
	"Publicidad: Remises La Corvina. Cruzamos el arroyo sin salpicarte la boina. Puntualidad isleña garantizada.",
	"Aviso parroquial: Se extravió una calabaza de mate curada con yerba misionera por la zona de los sauces. Recompensa en tortas fritas.",
	"Espacio publicitario: Colchones de Totora El Descanso. Si te despertás contracturado, te devolvemos dos atados de juncos.",
	"Aviso comercial: Pizzería El Camalote. Muzzarella elástica y masa a la piedra cocinada con leña de espinillo. Envío en canoa a todo el brazo del río.",
	"Publicidad: Alarma La Nutria. Avisamos cuando sube la marea a los gritos limpios. Sin cables ni internet.",
	"Publicidad: Plomería El Remanso. Destape de madrigueras inundadas y desagües de bañados con caña tacuara. Presupuestos sin cargo en la bajada del puente.",
	"Espacio publicitario: Escuela de Canotaje La Nutria Feliz. Clases de remo y timonel para principiantes. Aprendé a no chocar los troncos con estilo.",
	"Aviso parroquial: Trueque del Delta. Cambio dos bolsas de pasto tierno recién cortado por un vinilo de cumbia santafesina en buen estado. Tratar en el muelle tres.",
	"Publicidad: Fletes Fluviales Don Bigote. Mudanzas de rancho, traslado de fardos de totora y transporte de leña seca. Si flota, te lo llevamos.",
	"Espacio publicitario: Guardería de Camalotes El Espinillo. Dejá flotando tus plantas acuáticas en un ambiente seguro mientras te vas de viaje.",
	"Aviso comercial: Venta de Bombillas Autolimpiantes La Criolla. No se tapan ni con la yerba más polvorienta del almacén isleño.",
	"Publicidad: Herrería Ribereña El Sauce. Parrillas flotantes, asadores a la estaca inoxidables y ganchos para amarrar la canoa sin perder el sueño.",
	"Espacio publicitario: Cooperativa La Totora. Teñido artesanal de juncos y esterillas para que tu cueva parezca una postal de revista.",
	"Aviso parroquial: Atención vecinos del arroyo: se extravió un termo de acero inoxidable con calcomanías de cumbia. Si lo ven flotando, avisen a la radio.",
	"Publicidad: Zapatería El Carpincho Andariego. Botas de goma reforzadas para caminar el fango sin dejar la chancleta pegada en el fondo.",
	"Espacio publicitario: Panadería y Confitería El Hornero. Pastelitos de membrillo con masa hojaldrada y cañoncitos de dulce de leche para el mate de la tarde.",
	"Aviso comercial: Astillero Los Tres Bagres. Calafateado de botes a remo y reparación de quillas con brea natural del monte.",
	"Publicidad: Fumigaciones La Garza. Control ecológico de tábanos y jejenes con sapos adiestrados. Eficacia comprobada en todo el humedal.",
	"Espacio publicitario: Almacén de Ramos Generales La Bajada. Harina, grasa de pella, yerba por bolsa y alpargatas de todos los números.",
	"Aviso parroquial: Taller de Payadas y Guitarreadas Don Ceferino. Clases abiertas los sábados bajo el sauce llorón. Traer instrumento y mate propio.",
]

CARPINCHO_FORTUNES.extend(CARPINCHO_ADS)

# ---------------------------------------------------------------------------
# Frases de apertura, intro, lead-in y cierre radial
# ---------------------------------------------------------------------------

RADIO_INTROS: list[str] = [
	"Micrófono abierto, patas en el agua. Así arranca La Rockola.",
	"¿Quién dejó la pava en el control central? Bueno, no importa... ¡al aire en La Rockola!",
	"Directo desde el juncal para toda la cuenca: transmite La Rockola del Carpincho.",
	"Sintonizando la única frecuencia que no se hunde ni con la sudestada.",
	"Acomodate en el barro, fiera. Estás escuchando La Rockola del Carpincho.",
	"Secándonos al solcito de la orilla y metiendo buena música.",
	"En el aire de La Rockola del Carpincho.",
	"¡Buenas gente linda de La Rockola!",
	"La hora en La Rockola.",
	"Sintonizando La Rockola del Carpincho.",
	"¡Seguimos haciendo el aguante en La Rockola!",
	"Un matecito en La Rockola y seguimos.",
	"Transmite La Rockola del Carpincho.",
	"Che, buenas y santas gente linda; acá estamos en La Rockola del Carpincho.",
	"Posta, qué lindo estar acá en La Rockola; sintonizando buena onda.",
	"¡Al pelo la música en La Rockola del Carpincho!",
	"Tranqui en el agua, mate en mano... transmite La Rockola del Carpincho.",
	"Aire en el Delta, brisa en la cara y la pava silbando en la consola. ¡Arranca La Rockola!",
	"Con el agua a media pata y el mate recién espumado, abrimos los micrófonos en La Rockola.",
	"Se escucha el rumor del río de fondo y el mejor ritmo en el dial. ¡Bienvenidos a La Rockola del Carpincho!",
	"La marea sube pero la música sube todavía más. Sintonizás La Rockola desde la orilla.",
	"Dejamos la canoa bien amarrada al sauce y nos metemos al estudio. ¡En el aire La Rockola!",
	"Despertando a los bagres del fondo con buen volumen. ¡Transmite La Rockola del Carpincho!",
	"Olorcito a sauce mojado, mates amargos y la mejor compañía en el aire de La Rockola.",
	"Desde la cabina de madera sobre pilotes, tiramos buena vibra a todo el humedal. ¡Esto es La Rockola!",
	"Corré el camalote de la antena que salimos al aire con todo en La Rockola del Carpincho.",
	"Tardecita dorada en la ribera y nosotros listos para hacerte el aguante en La Rockola.",
]

RADIO_LEAD_INS: list[str] = [
	"Momento de rumiar una idea mientras chupás la bombilla...",
	"Llegó un mensaje en botella al terraplén; escuchá...",
	"Atendé lo que nos bajó la capitanía de la laguna.",
	"Aviso importante de la vecindad de los bañados.",
	"Pará la oreja que esto no te lo enseñan en la escuela de natación.",
	"Un consejo milenario directo del barro profundo.",
	"Momento de la galletita de la fortuna...",
	"Ojo al piojo con lo que dice el oráculo de La Rockola.",
	"Sabiduría carpinchera para el alma.",
	"Tiramos una frase para reflexionar mientras te tomás unos mates.",
	"Dice la fortuna del día...",
	"Atenti a esta reflexión carpinchera.",
	"Espacio publicitario en La Rockola.",
	"Atenti a este aviso de la comunidad carpinchera.",
	"Mensaje de nuestros queridos auspiciantes.",
	"Che, atenti al oráculo; sabiduría pura de la laguna.",
	"Posta, escuchate esta reflexión carpinchera.",
	"Pará la oreja; mirá lo que nos deja el oráculo hoy.",
	"Pará un segundo el remo que bajó línea el oráculo del pajonal.",
	"Atenti a la orilla, que el carpincho sabio nos dejó este mensaje.",
	"Dejá la pava en la mesa y abrí bien las orejas con esta reflexión.",
	"Mirá la frase que nos mandaron desde el fondo de los esteros.",
	"Anotate esta máxima isleña antes de cebar el próximo amargo.",
	"El oráculo de la ribera tiene un consejo que te va a volar la boina.",
	"Frená un cambio y escuchá lo que enseña la calma de la laguna.",
	"Palabra santa que llega navegando entre los camalotes.",
	"Abrí la mente y sentí la posta que nos trae la corriente.",
	"Para vos que andás medio a las corridas, prestale atención a esta joyita.",
]

RADIO_OUTROS: list[str] = [
	"Dejamos de parlotear y que hable el bajo. ¡Metele play!",
	"Acomodá el lomo en la orilla que este tema arranca al palo.",
	"Menos charla y más cumbia. ¡Pegale!",
	"¡Subile al parlante antes de que nos tape la marea!",
	"Se viene un clásico de aquellos... ¡hacete un espacio y bailá!",
	"Frenamos la charla pero la música no para. ¡Escuchate esto!",
	"¡Seguimos con más música!",
	"¡Que no decaiga!",
	"¡Pegale play que esto sigue!",
	"¡Metemos la próxima canción al toque!",
	"¡Seguimos de joda en La Rockola!",
	"¡Acomodate que se viene un temazo!",
	"¡Un carpinchazo de tema para vos; metele play!",
	"Tranqui en el agua, mate en mano... ¡a disfrutar lo que viene!",
	"¡Al pelo el ritmo; seguimos con todo en La Rockola!",
	"Posta, qué temazo se viene ahora; no te muevas de ahí.",
	"¡Basta de cháchara y que reviente el parche! ¡Metele play!",
	"¡Subile dos rayitas al volumen que este tema te levanta de la reposera!",
	"¡Agarrate fuerte de la borda que se viene un temazo al palo!",
	"¡A sacudirse el barro de las patas y meterle baile con esto que suena!",
	"¡Largá el remo un minuto y mandate a la pista con esta canción!",
	"¡Este tema te saca la fiaca de un tirón! ¡Dale gas!",
	"¡Temazo de aquellos para escuchar con la ventanilla baja y el viento en la cara!",
	"¡Dejate llevar por el compás que la tarde pide fiesta en la orilla!",
	"¡Volumen al mango que los carpinchos quieren cumbia!",
	"¡Acomodá el parlante mirando al río y disfrutá de este cañonazo musical!",
]

# ---------------------------------------------------------------------------
# Horas especiales en punto y segmentos modulares
# ---------------------------------------------------------------------------

SPECIAL_HOURS: dict[int, str] = {
	0: "Las doce de la noche en punto, arranca la trasnoche en La Rockola.",
	1: "Las una en punto, es hora de mimir.",
	2: "Las dos de la madrugada en punto, silencio en la laguna.",
	3: "Las tres de la mañana en punto, hora de los carpinchos sonámbulos.",
	4: "Las cuatro de la mañana en punto, el que no duerme pega en el palo.",
	5: "Las cinco de la mañana en punto, ya clarea en los bañados.",
	6: "Las seis de la mañana en punto, arriba que canta el chajá.",
	7: "Las siete de la mañana en punto, el agua está para unos buenos mates.",
	8: "Las ocho de la mañana en punto, arranca la jornada con toda la onda.",
	9: "Las nueve de la mañana en punto, el sol calienta la barranca.",
	10: "Las diez de la mañana en punto, una pastura tierna para picar.",
	11: "Las once de la mañana en punto, se siente el olorcito a comida.",
	12: "Las doce del mediodía en punto, hora de prender el fuego para el asado.",
	13: "Las una de la tarde en punto, la panza llena y el corazón contento.",
	14: "Las dos de la tarde en punto, sagrada hora de la siesta carpincha.",
	15: "Las tres de la tarde en punto, un chapuzón para refrescar las ideas.",
	16: "Las cuatro de la tarde en punto, salen esos mates con tortas fritas.",
	17: "Las cinco de la tarde en punto, la merienda no se negocia con nadie.",
	18: "Las seis de la tarde en punto, cae el solcito en el pajonal.",
	19: "Las siete de la tarde en punto, la tardecita pide buena música.",
	20: "Las ocho de la noche en punto, se va cerrando el boliche y abriendo la fiesta.",
	21: "Las nueve de la noche en punto, la mesa está servida en la madriguera.",
	22: "Las diez de la noche en punto, brindis con amigos y a disfrutar.",
	23: "Las once de la noche en punto, la última ronda antes de cerrar los ojales.",
}

HOUR_NAMES: list[str] = [
	"Las doce",
	"Las una",
	"Las dos",
	"Las tres",
	"Las cuatro",
	"Las cinco",
	"Las seis",
	"Las siete",
	"Las ocho",
	"Las nueve",
	"Las diez",
	"Las once",
]

MINUTE_SEGMENTS: list[str] = [
	"en punto.",
	"y cinco.",
	"y diez.",
	"y cuarto.",
	"y veinte.",
	"y veinticinco.",
	"y media.",
	"y treinta y cinco.",
	"menos veinte.",
	"menos cuarto.",
	"menos diez.",
	"menos cinco.",
]

# ---------------------------------------------------------------------------
# Clima: Lead-ins, condiciones y plantillas
# ---------------------------------------------------------------------------

DEFAULT_WEATHER_LOCATION: str = "San Miguel de Tucumán"
WEATHER_RAIN_THRESHOLD: int = 50

WEATHER_LEAD_INS: list[str] = [
	"El informe del tiempo carpincho nos canta la posta.",
	"Mirá por la ventana o pará la oreja, que así viene el clima.",
	"Atenti con el servicio meteorológico de La Rockola.",
	"Momento de chequear cómo viene la mano con el cielo.",
	"Pará un segundo el mate que te paso el parte meteorológico.",
]

WEATHER_TEMPLATES: list[str] = [
	# Plantilla 1: Directa y clásica
	"{lead} Tenemos {temp_str} de temperatura actual. Para hoy la mínima es de {min_today_str} y la máxima alcanzará los {max_today_str}. Para mañana esperamos {range_tomorrow_str}. {lluvia_desc}",
	# Plantilla 2: Centrada en la sensación térmica y perspectiva
	"{lead} La temperatura en este momento marca {temp_str}. Hoy el termómetro se moverá entre {min_today_str} de mínima y {max_today_str} de máxima. Mañana vamos a andar {range_tomorrow_str}. {lluvia_desc}",
	# Plantilla 3: Coloquial carpinchera
	"{lead} Clavamos {temp_str} en la laguna. Para lo que queda del día esperamos entre {min_today_str} y {max_today_str}. Y ojo a mañana que esperamos {range_tomorrow_str}. {lluvia_desc}",
]

# ---------------------------------------------------------------------------
# Charla de cabina: Pases y Reacciones
# ---------------------------------------------------------------------------

PASES_A_CLIMA: list[str] = [
	"Che {cohost}, asomate al bañado y decime si viene el pampero.",
	"{cohost}, ¿cómo está la temperatura para meter panzada al río?",
	"Tirame la data del cielo, {cohost}, que se me están enfriando las patas.",
	"Decime qué onda afuera, {cohost}, ¿sale mate caliente o tereré?",
	"A ver compadre {cohost}, cantame cómo pinta la mano meteorológica.",
	"Y para el tiempo, {cohost}, ¿cómo viene la mano?",
	"A ver, {cohost}, ¿qué nos canta el cielo hoy?",
	"{cohost}, tirate el parte meteorológico carpincho.",
	"¿Cómo viene la mano afuera, {cohost}?",
	"{cohost}, ¿salimos en cuero o aprontamos el paraguas?",
	"Contame qué dice el servicio meteorológico, {cohost}.",
	"¿Qué tenemos en el pronóstico para hoy, {cohost}?",
	"Che, {cohost}, ¿cómo pinta el clima en el bañado?",
	"Che {cohost}, con esta sudestada que amaga con subir el río, ¿qué dice el pronóstico?",
	"Decime {cohost}, con esta humedad que te riza hasta los bigotes, ¿se viene el chaparrón o zafamos?",
	"A ver {cohost}, asomate al muelle y decime si el viento del este nos trae agua.",
	"{cohost}, tirame la posta del tiempo: ¿está para meter panzada al río o nos refugiamos en la cueva?",
	"Che {cohost}, mirá cómo vuelan bajo las golondrinas... ¿qué marca el radar para hoy?",
	"Cantame los números del clima {cohost}, que la tarde está tan pesada que ni los mosquitos vuelan.",
	"¿Cómo viene la mano con el cielo {cohost}, sale sol para secar el cuero o preparamos el piloto?",
	"{cohost}, compadre de cabina, ¿cómo pinta el tiempo para los que andan navegando la cuenca?",
]

RADIO_HANDOFFS: list[str] = [
	"¿Cómo viene la mano afuera, che?",
	"Contame qué dice el servicio meteorológico.",
	"¿Qué tenemos en el pronóstico para hoy?",
	"Tirate esa data de la laguna.",
	"Pará que quiero saber qué dice el oráculo.",
	"¿Qué nos espera en el cielo, compadre?",
	"Tirame el parte meteorológico carpincho.",
]

REACCIONES_CLIMA: dict[str, list[str]] = {
	"calor": [
		"¡Mamita querida, qué calorón para estar en el agua todo el día!",
		"¡Hermoso para un chapuzón en la laguna con tereré!",
		"¡Pesadito el calor! No te olvides el protector solar.",
		"¡Está para quedarse a la sombra tomando mates fríos!",
		"¡Qué solazo! A buscar la sombrita del ceibo urgente.",
	],
	"frio": [
		"¡Fresquito para poncho! Metan más leña al fuego.",
		"¡Qué frescor, compadre! Salen esos mates bien calientes.",
		"¡Está para invernar abajo de la paja brava!",
		"¡Se vino el frío de golpe! A cuidar las orejas.",
		"¡Pucha que está fresco! Lindo para unas tortas fritas.",
	],
	"lluvia": [
		"¡Clima soñado de lluvia para andar chapoteando en el agua!",
		"¡Qué hermosura de agua! La laguna nos sonríe.",
		"¡Se viene el agua nomás! A disfrutar del olorcito a tierra mojada.",
		"¡Al pelo la lluvia para meter siesta carpincha!",
		"¡Chaparrón a la vista! El río va a estar una pinturita.",
	],
	"agradable": [
		"¡Una pinturita de día para andar al aire libre!",
		"¡Joya total! El clima ideal para unos amargos en la orilla.",
		"¡Ni frío ni calor, qué más querés para pasarla bomba!",
		"¡Clima perfecto, compadre! A disfrutarlo a pleno.",
		"¡Está de diez afuera! Ni una queja podemos meter.",
	],
}

REACCIONES_FORTUNA: list[str] = [
	"¡Olvídate! Mejor explicado, imposible.",
	"¡Uh, qué bárbaro! Me dejó recalculando.",
	"Tal cual, compadre... no le saques ni una coma.",
	"¡Mamita querida! Metiste el dedo en la llaga.",
	"Naaa, qué momento. Piel de carpincho se me puso.",
	"Tranqui, fiera... que no cunda el pánico en el pajonal.",
	"¡Qué personaje! Firmo abajo.",
	"¡Ja! Qué sabio el oráculo.",
	"¡Tal cual, compadre! La pura verdad.",
	"¡Qué lo tiró! Sabiduría pura de la laguna.",
	"¡Amén! Más claro, echale agua.",
	"¡Posta! Tomá nota de esa.",
	"¡Ojo al piojo! No tiene desperdicio.",
	"¡Una joyita de reflexión!",
	"¡Mirá vos! Justo lo que hacía falta escuchar.",
	"¡Palabra santa! A guardarla en el corazón.",
	"¡De una! Nada más que agregar.",
	"¡Clarito como agua de arroyo en bajante!",
	"¡Naaa, qué filósofo de bañado tenemos hoy!",
	"¡Aplaudo de pie con las dos patas delanteras!",
	"¡Esa frase te acomoda las ideas de una sola cebada!",
	"¡Una obra de arte! Ni un poeta del Delta lo decía mejor.",
	"¡Totalmente! Guardalo en un frasco de mermelada y no lo pierdas.",
	"¡Qué profundidad criolla! Me quedé sin palabras, compadre.",
	"¡Eso no fue un consejo, fue una caricia al alma!",
	"¡Para ponerlo en un cartelito de madera en la entrada del rancho!",
	"¡Posta pura! Al que no le guste, que vaya a rumiar pasto amargo.",
]

RADIO_REACTIONS: list[str] = [
	"¡Qué lo tiró, che!",
	"Mirá vos, qué momento.",
	"Lindo momento para unos buenos mates.",
	"Una pinturita.",
	"Totalmente, compadre.",
	"Tal cual, fiera.",
	"¡Qué temazo metiste!",
	"La posta pura.",
	"¡Ojo al piojo!",
	"Así se habla en el pago.",
	"¡Qué pedazo de tema, por favor!",
	"Ese solo te afloja hasta las junturas.",
	"¡Inolvidable! Para escucharlo en loop todo el domingo.",
	"¡Qué ritmo sabroso, compadre!",
	"Te deja con el corazón saltando como boga en la red.",
	"¡Una locura total! Música de la buena.",
	"Ese tema te levanta cualquier día nublado.",
	"¡Qué swing ribereño metió esa banda!",
]

# ---------------------------------------------------------------------------
# NLP: Stopwords, Detección de Idioma y Verbos
# ---------------------------------------------------------------------------

KNOWN_SPANISH_DBS: set[str] = {
	"amistad",
	"argentina",
	"arte",
	"artistas",
	"asimov",
	"chistes",
	"ciencia",
	"citas",
	"deprimente",
	"es",
	"es-ar",
	"es-la",
	"familia",
	"famosos",
	"filosofia",
	"folklore",
	"humanos",
	"humor",
	"informatica",
	"lao-tse",
	"lemas",
	"leydemurphy",
	"libertad",
	"literatura",
	"nietzsche",
	"pintadas",
	"poder",
	"proverbios",
	"refranes",
	"sabiduria",
	"schopenhauer",
	"sentimientos",
	"tango",
	"varios",
	"varios-pre",
	"verdad",
	"vida",
}

SPANISH_CHARS: set[str] = set("áéíóúüñÁÉÍÓÚÜÑ¿¡")

COMMON_SPANISH_WORDS: set[str] = {
	"a",
	"al",
	"algo",
	"algunos",
	"amigo",
	"amigos",
	"ante",
	"antes",
	"aquel",
	"aquella",
	"aquello",
	"aquí",
	"asado",
	"así",
	"bien",
	"boda",
	"buen",
	"buena",
	"buenas",
	"bueno",
	"buenos",
	"cada",
	"carpincho",
	"casi",
	"che",
	"como",
	"con",
	"contra",
	"cosa",
	"cosas",
	"cual",
	"cuando",
	"cuanto",
	"cumbia",
	"cuál",
	"cuándo",
	"cuánto",
	"cómo",
	"de",
	"del",
	"desde",
	"donde",
	"dos",
	"durante",
	"dónde",
	"e",
	"el",
	"ella",
	"ellas",
	"ellos",
	"en",
	"entre",
	"era",
	"es",
	"esa",
	"esas",
	"ese",
	"eso",
	"esos",
	"esta",
	"estaba",
	"estas",
	"este",
	"esto",
	"estos",
	"está",
	"familia",
	"feliz",
	"fernet",
	"fiesta",
	"frase",
	"fue",
	"gente",
	"gracias",
	"gran",
	"ha",
	"haber",
	"había",
	"hace",
	"hacer",
	"hacia",
	"hasta",
	"hay",
	"hola",
	"hoy",
	"la",
	"las",
	"le",
	"les",
	"lo",
	"los",
	"mando",
	"mas",
	"mate",
	"mates",
	"me",
	"medio",
	"mejor",
	"menos",
	"mi",
	"mientras",
	"mis",
	"mismo",
	"mucho",
	"muy",
	"más",
	"mí",
	"mía",
	"mío",
	"música",
	"nada",
	"ni",
	"no",
	"noche",
	"nos",
	"nosotros",
	"nuestra",
	"nuestras",
	"nuestro",
	"nuestros",
	"nunca",
	"o",
	"ojo",
	"oráculo",
	"otra",
	"otro",
	"otros",
	"para",
	"pero",
	"play",
	"poco",
	"por",
	"porque",
	"posta",
	"proverbio",
	"que",
	"quien",
	"quienes",
	"quién",
	"qué",
	"refrán",
	"sabiduría",
	"se",
	"ser",
	"si",
	"siempre",
	"sin",
	"sobre",
	"son",
	"su",
	"sus",
	"sí",
	"también",
	"tanto",
	"tarde",
	"te",
	"tema",
	"temas",
	"temazo",
	"tiempo",
	"tiene",
	"todo",
	"todos",
	"tu",
	"tus",
	"un",
	"una",
	"unas",
	"uno",
	"unos",
	"va",
	"veces",
	"vez",
	"vida",
	"y",
	"ya",
	"él",
}

COMMON_ENGLISH_WORDS: set[str] = {
	"about",
	"all",
	"an",
	"and",
	"are",
	"as",
	"at",
	"be",
	"been",
	"but",
	"by",
	"call",
	"can",
	"come",
	"could",
	"day",
	"did",
	"do",
	"down",
	"each",
	"find",
	"first",
	"for",
	"from",
	"get",
	"go",
	"had",
	"has",
	"have",
	"he",
	"her",
	"him",
	"his",
	"how",
	"i",
	"if",
	"in",
	"into",
	"is",
	"it",
	"its",
	"like",
	"look",
	"made",
	"make",
	"many",
	"may",
	"more",
	"my",
	"no",
	"not",
	"now",
	"number",
	"on",
	"one",
	"or",
	"other",
	"out",
	"part",
	"people",
	"said",
	"see",
	"she",
	"so",
	"some",
	"than",
	"that",
	"the",
	"their",
	"them",
	"then",
	"there",
	"these",
	"they",
	"this",
	"time",
	"two",
	"up",
	"use",
	"was",
	"water",
	"way",
	"we",
	"were",
	"what",
	"when",
	"which",
	"who",
	"will",
	"with",
	"would",
	"write",
	"you",
	"your",
}

COMMON_SPANISH_VERBS: set[str] = {
	"acaba",
	"acaban",
	"acabó",
	"afirma",
	"afirman",
	"afirmó",
	"ama",
	"aman",
	"amaba",
	"amó",
	"anda",
	"andan",
	"andaba",
	"anduvo",
	"aprende",
	"aprenden",
	"aprendió",
	"ayuda",
	"ayudan",
	"ayudó",
	"basta",
	"bastan",
	"bastó",
	"bebe",
	"beben",
	"bebió",
	"brilla",
	"brillan",
	"brilló",
	"busca",
	"buscan",
	"buscaba",
	"buscó",
	"cae",
	"caen",
	"caía",
	"calla",
	"callan",
	"calló",
	"cambia",
	"cambian",
	"cambió",
	"camina",
	"caminan",
	"caminó",
	"canta",
	"cantan",
	"cantó",
	"cayó",
	"cayeron",
	"come",
	"comen",
	"comía",
	"comió",
	"comienza",
	"comienzan",
	"comenzó",
	"conoce",
	"conocen",
	"conoció",
	"corre",
	"corren",
	"corrió",
	"cree",
	"creen",
	"creía",
	"creyó",
	"creyeron",
	"cuesta",
	"cuestan",
	"costó",
	"cura",
	"curan",
	"curó",
	"da",
	"daba",
	"daban",
	"damos",
	"dan",
	"dará",
	"darán",
	"das",
	"dé",
	"decía",
	"decían",
	"decimos",
	"decís",
	"deja",
	"dejaba",
	"dejan",
	"dejar",
	"dejes",
	"dejó",
	"den",
	"dice",
	"dicen",
	"dices",
	"digo",
	"diga",
	"digan",
	"dijo",
	"dijeron",
	"dio",
	"dieron",
	"dirá",
	"dirán",
	"doler",
	"doy",
	"duele",
	"duelen",
	"dolió",
	"duerme",
	"duermen",
	"durmió",
	"duda",
	"dudan",
	"dudó",
	"dura",
	"duran",
	"duró",
	"empieza",
	"empiezan",
	"empezó",
	"encuentra",
	"encuentran",
	"encontró",
	"enseña",
	"enseñan",
	"enseñó",
	"entiende",
	"entienden",
	"entendió",
	"entra",
	"entran",
	"entró",
	"era",
	"eran",
	"eres",
	"es",
	"escucha",
	"escuchan",
	"escuchó",
	"espera",
	"esperaba",
	"esperan",
	"esperó",
	"está",
	"estaba",
	"estaban",
	"estamos",
	"están",
	"estará",
	"estarán",
	"estás",
	"esté",
	"estén",
	"estoy",
	"estuvo",
	"estuvieron",
	"falta",
	"faltan",
	"faltó",
	"fue",
	"fueron",
	"gana",
	"ganan",
	"ganó",
	"gusta",
	"gustan",
	"gustó",
	"ha",
	"había",
	"habla",
	"hablaba",
	"hablan",
	"habló",
	"habrá",
	"hace",
	"hacemos",
	"hacen",
	"haces",
	"hacés",
	"hacía",
	"hacían",
	"haga",
	"hagan",
	"hago",
	"han",
	"hará",
	"harán",
	"has",
	"hay",
	"haya",
	"hayan",
	"he",
	"hemos",
	"hizo",
	"hicieron",
	"honra",
	"honran",
	"honró",
	"hubo",
	"huye",
	"huyen",
	"huyó",
	"iba",
	"iban",
	"importa",
	"importan",
	"importó",
	"irá",
	"irán",
	"juzga",
	"juzgan",
	"juzgó",
	"llega",
	"llegan",
	"llegó",
	"lleva",
	"llevan",
	"llevó",
	"llora",
	"lloran",
	"lloró",
	"madruga",
	"madrugan",
	"madrugó",
	"manda",
	"mandan",
	"mandó",
	"mira",
	"miraba",
	"miran",
	"miró",
	"morir",
	"muere",
	"mueren",
	"murió",
	"nace",
	"nacen",
	"nació",
	"nada",
	"nadan",
	"nadó",
	"necesita",
	"necesitan",
	"necesitó",
	"oculta",
	"ocultan",
	"ocultó",
	"odia",
	"odian",
	"odió",
	"olvida",
	"olvidan",
	"olvidó",
	"oye",
	"oyen",
	"oyó",
	"paga",
	"pagan",
	"pagó",
	"parece",
	"parecen",
	"pareció",
	"parte",
	"parten",
	"partió",
	"pasa",
	"pasan",
	"pasó",
	"pide",
	"piden",
	"pidió",
	"piensa",
	"piensan",
	"pensó",
	"pierde",
	"pierden",
	"perdió",
	"puede",
	"pueden",
	"puedes",
	"puedo",
	"podemos",
	"podía",
	"podían",
	"podés",
	"podrá",
	"podrán",
	"ponga",
	"pongan",
	"pone",
	"ponemos",
	"ponen",
	"pones",
	"ponés",
	"pongo",
	"ponía",
	"ponían",
	"pondrá",
	"pondrán",
	"pudo",
	"pudieron",
	"pueda",
	"puedan",
	"puso",
	"pusieron",
	"queda",
	"quedan",
	"quedó",
	"quema",
	"queman",
	"quemó",
	"quiere",
	"quieren",
	"quieres",
	"quiero",
	"queremos",
	"querés",
	"quería",
	"querían",
	"quiera",
	"quieran",
	"quiso",
	"quisieron",
	"querrá",
	"querrán",
	"recibe",
	"reciben",
	"recibió",
	"recuerda",
	"recuerdan",
	"recordó",
	"reflexiona",
	"reflexionan",
	"reflexionó",
	"rie",
	"ríe",
	"rien",
	"ríen",
	"rió",
	"rompe",
	"rompen",
	"rompió",
	"sabe",
	"sabemos",
	"saben",
	"sabes",
	"sabés",
	"sabía",
	"sabían",
	"sabrá",
	"sabrán",
	"sale",
	"salen",
	"salió",
	"salva",
	"salvan",
	"salvó",
	"se",
	"sé",
	"sea",
	"sean",
	"seguir",
	"sepa",
	"sepan",
	"será",
	"serán",
	"sería",
	"serían",
	"siente",
	"sienten",
	"sintió",
	"sigue",
	"siguen",
	"siguió",
	"sirve",
	"sirven",
	"sirvió",
	"sobra",
	"sobran",
	"sobró",
	"somos",
	"son",
	"sos",
	"soy",
	"suena",
	"suenan",
	"sonó",
	"sufre",
	"sufren",
	"sufrió",
	"supo",
	"supieron",
	"teme",
	"temen",
	"temió",
	"tendrá",
	"tendrán",
	"tenga",
	"tengan",
	"tengo",
	"tenemos",
	"tenía",
	"tenían",
	"tiene",
	"tienen",
	"tienes",
	"tenés",
	"termina",
	"terminan",
	"terminó",
	"toca",
	"tocan",
	"tocó",
	"toques",
	"toma",
	"toman",
	"tomó",
	"trae",
	"traen",
	"trajo",
	"tuvo",
	"tuvieron",
	"va",
	"vamos",
	"van",
	"vas",
	"vaya",
	"vayan",
	"ve",
	"vea",
	"vean",
	"veía",
	"veían",
	"vemos",
	"ven",
	"vendrá",
	"vendrán",
	"venga",
	"vengan",
	"vengo",
	"venimos",
	"venir",
	"venís",
	"venía",
	"venían",
	"veo",
	"verá",
	"verán",
	"verás",
	"ves",
	"vino",
	"vinieron",
	"vio",
	"vieron",
	"vive",
	"viven",
	"vivía",
	"vivió",
	"voló",
	"volar",
	"volvió",
	"volver",
	"voy",
	"vuela",
	"vuelan",
	"vuelve",
	"vuelven",
	# Formas verbales comunes adicionales (refranes, proverbios, voseo y coloquial)
	"acomoda",
	"acomodan",
	"acomodó",
	"arregla",
	"arreglan",
	"arregló",
	"avisa",
	"avisan",
	"avisamos",
	"avisó",
	"baila",
	"bailan",
	"bailó",
	"baja",
	"bajan",
	"bajó",
	"bajá",
	"calienta",
	"calientan",
	"calientes",
	"calentó",
	"calentar",
	"cierra",
	"cierran",
	"cerró",
	"compite",
	"compiten",
	"compitió",
	"competir",
	"concluye",
	"concluyen",
	"concluyó",
	"consigue",
	"consiguen",
	"consiguió",
	"conseguís",
	"crece",
	"crecen",
	"creció",
	"cruza",
	"cruzan",
	"cruzamos",
	"cruzó",
	"cuenta",
	"cuentan",
	"cuente",
	"cuenten",
	"cuentes",
	"contó",
	"cuida",
	"cuidan",
	"cuidamos",
	"cuidó",
	"cuidar",
	"descansa",
	"descansan",
	"descansó",
	"descansar",
	"despeina",
	"despeinan",
	"despeinó",
	"despierta",
	"despiertan",
	"despertó",
	"despertás",
	"devuelve",
	"devuelven",
	"devolvemos",
	"devolvió",
	"disfruta",
	"disfrutan",
	"disfrutás",
	"disfrutó",
	"disfrutá",
	"fija",
	"fijan",
	"fijó",
	"fijate",
	"flota",
	"flotan",
	"flotó",
	"flotar",
	"hacé",
	"juega",
	"juegan",
	"jugó",
	"limpia",
	"limpian",
	"limpió",
	"mata",
	"matan",
	"mató",
	"mete",
	"meten",
	"metió",
	"metele",
	"pesa",
	"pesan",
	"pesó",
	"pica",
	"pican",
	"piquen",
	"picó",
	"pida",
	"pidan",
	"pidas",
	"recibirás",
	"relaja",
	"relajan",
	"relajó",
	"relajá",
	"respira",
	"respiran",
	"respiró",
	"salpica",
	"salpican",
	"salpicar",
	"salpicó",
	"separa",
	"separan",
	"separó",
	"sube",
	"suben",
	"subió",
	"subile",
	"tira",
	"tiran",
	"tiró",
	"tomás",
	"tomate",
	"traiga",
	"traigan",
	"une",
	"unen",
	"unió",
	"vale",
	"valen",
	"valió",
	"viene",
	"vienen",
	"viaja",
	"viajan",
	"viajó",
}

VERBAL_SUFFIXES_REGEX = re.compile(
	r"^[a-záéíóúñ]{3,}(?:aron|ieron|aban|iendo|ando|aría|arían|ería|erían|iría|irían|ará|arán|arás|erá|erán|erás|irá|irán|irás|aste|iste|ábamos|áramos|iéramos|asen|iesen|ase|iese)$"
)

FORBIDDEN_FORMAT_CHARS: set[str] = set(r"*\/|+=>%^~@#$_[]{}&")

# ---------------------------------------------------------------------------
# Blacklist: Mal gusto y Jerga IA/Robot
# ---------------------------------------------------------------------------

PROFANITY_TERMS: set[str] = {
	"boluda",
	"boludas",
	"boludo",
	"boludos",
	"cabron",
	"cabrón",
	"cabrones",
	"carajo",
	"carajos",
	"chingada",
	"chingar",
	"chota",
	"chotas",
	"choto",
	"chotos",
	"chupala",
	"concha",
	"conchas",
	"conchuda",
	"conchudas",
	"conchudo",
	"conchudos",
	"culiada",
	"culiadas",
	"culiado",
	"culiados",
	"culiao",
	"culiaos",
	"culo",
	"culos",
	"estupida",
	"estúpida",
	"estupidas",
	"estúpidas",
	"estupido",
	"estúpido",
	"estupidos",
	"estúpidos",
	"forra",
	"forras",
	"forro",
	"forros",
	"imbecil",
	"imbécil",
	"imbeciles",
	"imbéciles",
	"malparida",
	"malparido",
	"mamada",
	"mamadas",
	"maricon",
	"maricón",
	"maricones",
	"mierda",
	"mierdas",
	"ojete",
	"ojetes",
	"orto",
	"ortos",
	"pelotuda",
	"pelotudas",
	"pelotudo",
	"pelotudos",
	"pendeja",
	"pendejas",
	"pendejo",
	"pendejos",
	"pija",
	"pijas",
	"puta",
	"putas",
	"puto",
	"putos",
	"sorete",
	"soretes",
	"tarada",
	"taradas",
	"tarado",
	"tarados",
	"verga",
	"vergas",
}

PROFANITY_PHRASES: list[str] = [
	"hijo de puta",
	"hija de puta",
	"hijos de puta",
	"hdp",
	"la puta madre",
	"la concha de",
	"andate a la mierda",
	"la puta que te",
]

AI_ROBOTIC_PHRASES: list[str] = [
	"como modelo de lenguaje",
	"como un modelo de lenguaje",
	"modelo de lenguaje",
	"en que puedo ayudarte",
	"en qué puedo ayudarte",
	"en qué puedo asistirte",
	"en que puedo asistirte",
	"procesando datos",
	"sistema operativo",
	"algoritmo",
	"algoritmos",
	"error 404",
	"404 not found",
	"código de error",
	"inteligencia artificial",
	"red neuronal",
	"redes neuronales",
	"asistente virtual",
	"asistente de ia",
	"asistente ia",
	"open ai",
	"openai",
	"chatgpt",
	"deepmind",
	"prompt",
	"prompts",
	"lenguaje de programación",
	"nullpointerexception",
	"segmentation fault",
	"stack overflow",
]
